name: zxing_lib
description: A Dart port of zxing that encode and decode multiple 1D/2D barcodes, Supported qrcode, pdf417, oned, maxicode, datamatrix, aztec.
version: 1.0.0
homepage: https://shirne.github.io/
repository: https://github.com/shirne/zxing-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl:
  charset: ^2.0.0

dev_dependencies:
  test:
  fixnum: ^1.0.1
  lints:
  image: ^4.0.17
  collection:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

